#!/bin/bash

sudo cp -rf ./config/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbdev.conf
sudo cp -rf ./boot/config-nomal.txt /boot/config.txt
sudo echo "hdmi_force_hotplug=1" >> /boot/config.txt
sudo cp ./boot/cmdline.txt /boot/

sudo sync
sudo sync

echo "reboot now"
sudo reboot
