#!/bin/bash

if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
fi
dpkg -l | grep -q "xserver-xorg-input-libinput"
if [ $? -eq 0 ]; then
sudo apt-get purge xserver-xorg-input-libinput -y
fi
if [ ! -d /etc/X11/xorg.conf.d ]; then
sudo mkdir -p /etc/X11/xorg.conf.d
fi

sudo cp ./overlays/tft35a-overlay.dtb /boot/overlays/
sudo cp ./overlays/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
sudo cp -rf ./boot/config-35.txt /boot/config.txt
sudo cp -rf ./config/99-calibration.conf-35  /etc/X11/xorg.conf.d/99-calibration.conf
sudo cp -rf ./config/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbdev.conf
sudo cp ./boot/cmdline.txt /boot/

echo "reboot now"
sudo reboot
