#!/bin/bash

if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
fi
if [ ! -d /etc/X11/xorg.conf.d ]; then
sudo mkdir -p /etc/X11/xorg.conf.d
fi

sudo cp -rf ./boot/config-40-HDMI-480x320.txt /boot/config.txt
sudo cp ./boot/cmdline.txt /boot/
sudo cp -rf ./config/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbdev.conf
sudo cp -rf ./config/99-calibration.conf-40-HDMI /etc/X11/xorg.conf.d/99-calibration.conf

sudo echo "reboot now"
sudo reboot

