#!/bin/bash

sudo cp -rf ./boot/config-70-HDMI-1024x600.txt /boot/config.txt
sudo cp ./boot/cmdline.txt /boot/ 
sudo cp -rf ./config/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbdev.conf 
if [ ! -d /etc/X11/xorg.conf.d ]; then 
sudo mkdir /etc/X11/xorg.conf.d 
fi
sudo cp ./config/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
sudo apt-get update
sudo apt-get install xserver-xorg-input-libinput

echo "reboot now"
sudo reboot
